base_model: mistralai/Mistral-Nemo-Instruct-2407
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: mistral
datasets:
  - path: /home/peterjin/mnt/axolotl_train/nq_train/e5/gemma2-9B-chat/train.jsonl
    ds_type: json
    type: chat_template
    chat_template: mistral
    field_messages: messages
    message_field_role: role
    message_field_content: content
    roles:
      user:
        - user
      system:
        - system
      assistant:
        - assistant

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
# output_dir: /home/peterjin/mnt/axolotl_output/nq_train-e5-llama31-8B-chat-epoch4-lr1e-5
output_dir: /home/peterjin/mnt/axolotl_output/debug

sequence_len: 16384 # 24576 can be supported by 8 h100s, 
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

wandb_project: RAG-tune-llm
wandb_entity: uiuc-dmg
wandb_watch:
# wandb_name: nq_train-e5-llama31-8B-chat-epoch4-lr1e-5
wandb_name: debug
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 4
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 1e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.05
evals_per_epoch: 1
eval_table_size:
saves_per_epoch: 1
save_total_limit: 10
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <unk>
